# mosquitto/mosquitto.conf
# Broker MQTT para receber dados do edge (Python bridge)
# Restringir acesso à porta 1883 pelo Security Group da EC2

listener 1883
allow_anonymous true

# Para produção: desabilite anonymous e use senha
# password_file /mosquitto/config/passwd

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
